### PR TITLE
Fix empty webpage

### LINKED ISSUE #13: website is broken

### PR DESCRIPTION
**Pull request by alphatrl**

### CODE REVIEW

File: src/components/ShopList/index.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ class ShopList extends Component {
           longitude: position.coords.longitude,
         },
       });
-    }, console.error);
+    }, console.error());
```
Comment (duncanleo) [inline src/components/ShopList/index.js]: I think passing the `console.error` as a variable might be correct... this calls `console.error` with no arguments

File: src/components/Shop/index.js [hunk 2]
```diff
@@ -9,17 +9,23 @@ const Shop = ({ shop, distance }) => {
...
     return `${chain} @ ${title}`;
   };
+
   function openMapApp(shopCoordinates) {
-    const isAppleOS = navigator.platform.match(/(iPhone|iPod|iPad)/i)?true:false;
+    const isAppleOS = navigator.platform.match(/(iPhone|iPod|iPad)/i);
 
     // Open Apple Maps if OS is iOS
-    if (isAppleOS) {
+    if (isAppleOS != null) {
```
Comment (duncanleo) [inline src/components/Shop/index.js]: could you use triple equals? `===`

Alternatively I think doing 
```js
/(iPhone|iPod|iPad)/i.test(navigator.platform)
```
should return a boolean

**Review by duncanleo — CHANGES_REQUESTED** [review]
minor nits

**Review by duncanleo — APPROVED** [review]

**Comment by duncanleo** [comment]
@alphatrl feel free to merge!
